const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Comment = sequelize.define('Comment', {
    content: {
        type: DataTypes.TEXT,
        allowNull: false
    }
    // UserId and CampaignId will be auto-generated by associations in index.js
});

module.exports = Comment;
